// The scenario data the engine is tested against. The rows that were here
// before the engine existed are hand-authored and unchanged; the rows between
// them are the resolutions those steps used to sweep past in one go, added
// when every step became a single resolution. Any correction to a row belongs
// in the commit that makes it.

export const GOLDEN = {
  "conservative-stalemate": [
    {"title":"Solo's upkeep: fading trigger","board":"A5 B5 C5","stack":"Fading(C)"},
    {"title":"S → S","board":"A5 B5 C4","stack":"C>C | Fading(C)"},
    {"title":"T1 → S","board":"A4 B5 C4","stack":"A>C | C>C | Fading(C)"},
    {"title":"S → T1","board":"A4 B5 C3","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S","board":"A4 B4 C3","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S → T2","board":"A4 B4 C2","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S again","board":"A4 B3 C2","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Solo lets T2 → S resolve","board":"A4 B3 CxB","stack":"C exiled > Return nothing | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Twin resets T2 correctly","board":"A4 B2 CxB","stack":"B>B | C exiled > Return nothing | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → T2 resolves","board":"A4 Bx CxB","stack":"B exiled > Return B, C | C exiled > Return nothing | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Return(T2¹) resolves — T2² and S² return","board":"A4 B5! C5!","stack":"C exiled > Return nothing | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S¹ exiled → Return nothing resolves","board":"A4 B5! C5!","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S¹→T2¹ resolves","board":"A4 B5! C5!","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1 resets before 4 can strand it","board":"A3 B5! C5!","stack":"A>A | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1→T1 resolves","board":"Ax B5! C5!","stack":"A exiled > Return A | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1¹ exiled → Return T1¹ resolves","board":"A5! B5! C5!","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2¹→S¹ resolves","board":"A5! B5! C5!","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"S¹→T1¹ resolves","board":"A5! B5! C5!","stack":"A>C | C>C | Fading(C)"},
    {"title":"T1¹→S¹ resolves","board":"A5! B5! C5!","stack":"C>C | Fading(C)"},
    {"title":"S¹→S¹ resolves","board":"A5! B5! C5!","stack":"Fading(C)"},
    {"title":"Fading(S¹) resolves","board":"A5! B5! C5!","stack":""},
    {"title":"Position stabilizes","board":"A5! B5! C5!","stack":""},
  ],
  "ab-tests-c-correct": [
    {"title":"Solo's upkeep: fading trigger","board":"A5 B5 C5","stack":"Fading(C)"},
    {"title":"S → S","board":"A5 B5 C4","stack":"C>C | Fading(C)"},
    {"title":"T1 → S","board":"A4 B5 C4","stack":"A>C | C>C | Fading(C)"},
    {"title":"S → T1","board":"A4 B5 C3","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S","board":"A4 B4 C3","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S → T2","board":"A4 B4 C2","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S again","board":"A4 B3 C2","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Twin sets the trap: T2 → T2","board":"A4 B2 C2","stack":"B>B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → T2 resolves","board":"A4 Bx C2","stack":"B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Solo resets S","board":"A4 Bx C1","stack":"C>C | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S→S resolves","board":"A4 Bx Cx","stack":"C exiled > Return C | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Return(S¹) resolves — S² returns","board":"A4 Bx C5!","stack":"B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1 has to reset too","board":"A3 Bx C5!","stack":"A>A | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1 → T1 resolves","board":"Ax Bx C5!","stack":"A exiled > Return A | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1¹ exiled → Return T1¹ resolves","board":"A5! Bx C5!","stack":"B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2¹ exiled → Return T2¹ resolves","board":"A5! B5! C5!","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Back to the stalemate","board":"A5! B5! C5!","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
  ],
  "ab-tests-c-mistake": [
    {"title":"Solo's upkeep: fading trigger","board":"A5 B5 C5","stack":"Fading(C)"},
    {"title":"S → S","board":"A5 B5 C4","stack":"C>C | Fading(C)"},
    {"title":"T1 → S","board":"A4 B5 C4","stack":"A>C | C>C | Fading(C)"},
    {"title":"S → T1","board":"A4 B5 C3","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S","board":"A4 B4 C3","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S → T2","board":"A4 B4 C2","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S again","board":"A4 B3 C2","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Twin sets the trap: T2 → T2","board":"A4 B2 C2","stack":"B>B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → T2 resolves","board":"A4 Bx C2","stack":"B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Solo counter-attacks instead","board":"A4 Bx C1","stack":"C>A | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S → T1 resolves — and it looks like it worked","board":"AxC Bx C1","stack":"A exiled > Return nothing | B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1 exiled → Return nothing resolves","board":"AxC Bx C1","stack":"B exiled > Return B | B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2¹ exiled → Return T2¹ resolves","board":"AxC B5! C1","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2¹ → S¹ resolves — S is exiled forever","board":"AxC B5! CxB","stack":"C exiled > Return A | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S¹'s leave trigger hands T1¹ back","board":"A5! B5! CxB","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Outcome","board":"A5! B5! CxB","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
  ],
  "c-tests-ab-mistake": [
    {"title":"Solo's upkeep: fading trigger","board":"A5 B5 C5","stack":"Fading(C)"},
    {"title":"S → S","board":"A5 B5 C4","stack":"C>C | Fading(C)"},
    {"title":"T1 → S","board":"A4 B5 C4","stack":"A>C | C>C | Fading(C)"},
    {"title":"S → T1","board":"A4 B5 C3","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S","board":"A4 B4 C3","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S → T2","board":"A4 B4 C2","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2 → S again","board":"A4 B3 C2","stack":"B>C | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Solo lets T2 → S resolve","board":"A4 B3 CxB","stack":"C exiled > Return nothing | C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"S exiled → Return nothing resolves","board":"A4 B3 CxB","stack":"C>B | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"Twin gets greedy","board":"A4 BxC CxB","stack":"B exiled > Return C | B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2's leave trigger resolves","board":"A4 BxC C5!","stack":"B>C | C>A | A>C | C>C | Fading(C)"},
    {"title":"T2¹ → S¹ fails","board":"A4 BxC C5!","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"T1 must protect itself","board":"A3 BxC C5!","stack":"A>A | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1→T1 resolves","board":"Ax BxC C5!","stack":"A exiled > Return A | C>A | A>C | C>C | Fading(C)"},
    {"title":"T1¹ exiled → Return T1¹ resolves","board":"A5! BxC C5!","stack":"C>A | A>C | C>C | Fading(C)"},
    {"title":"S¹→T1¹ resolves","board":"A5! BxC C5!","stack":"A>C | C>C | Fading(C)"},
    {"title":"T1¹→S¹ resolves","board":"A5! BxC C5!","stack":"C>C | Fading(C)"},
    {"title":"S¹→S¹ resolves","board":"A5! BxC C5!","stack":"Fading(C)"},
    {"title":"Fading(S¹) resolves","board":"A5! BxC C5!","stack":""},
    {"title":"T1 returns, T2¹ does not","board":"A5! BxC C5!","stack":""},
  ],
  "duel-permanent-exile": [
    {"title":"One Wave each","board":"K5 Z5 D","stack":""},
    {"title":"Z → K","board":"K5 Z4 D","stack":"Z>K"},
    {"title":"Z → Z on top","board":"K5 Z3 D","stack":"Z>Z | Z>K"},
    {"title":"Z → Z resolves — Zakk can no longer answer anything","board":"K5 Zx D","stack":"Z exiled > Return Z | Z>K"},
    {"title":"K → D","board":"K4 Zx D","stack":"K>D | Z exiled > Return Z | Z>K"},
    {"title":"K → K on top","board":"K3 Zx D","stack":"K>K | K>D | Z exiled > Return Z | Z>K"},
    {"title":"K → K resolves","board":"Kx Zx D","stack":"K exiled > Return K | K>D | Z exiled > Return Z | Z>K"},
    {"title":"Return(K¹) resolves — K² returns","board":"K5! Zx D","stack":"K>D | Z exiled > Return Z | Z>K"},
    {"title":"K¹ → D resolves — D is gone for good","board":"K5! Zx DxK","stack":"Z exiled > Return Z | Z>K"},
    {"title":"Return(Z¹) resolves — Z² returns","board":"K5! Z5! DxK","stack":"Z>K"},
    {"title":"Z¹→K¹ resolves","board":"K5! Z5! DxK","stack":""},
    {"title":"Both Waves back at five","board":"K5! Z5! DxK","stack":""},
  ],
  "duel-exile-war": [
    {"title":"Z → K","board":"K2 Z2","stack":"Z>K"},
    {"title":"K → Z","board":"K1 Z2","stack":"K>Z | Z>K"},
    {"title":"Z → K","board":"K1 Z1","stack":"Z>K | K>Z | Z>K"},
    {"title":"Z → Z — the mistake","board":"K1 Z0","stack":"Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K → K on top","board":"K0 Z0","stack":"K>K | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K→K resolves","board":"Kx Z0","stack":"K exiled > Return K | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"Return(K¹) resolves — K² comes back at five","board":"K5! Z0","stack":"Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K² → Z","board":"K4! Z0","stack":"K>Z | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K² → K² on top","board":"K3! Z0","stack":"K>K | K>Z | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K²→K² resolves","board":"Kx Z0","stack":"K exiled > Return K | K>Z | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K² exiled → Return K² resolves","board":"K5! Z0","stack":"K>Z | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"K² → Z resolves — Z is exiled forever","board":"K5! ZxK","stack":"Z exiled > Return nothing | Z>Z | Z>K | K>Z | Z>K"},
    {"title":"Z exiled → Return nothing resolves","board":"K5! ZxK","stack":"Z>Z | Z>K | K>Z | Z>K"},
    {"title":"Z→Z resolves","board":"K5! ZxK","stack":"Z>K | K>Z | Z>K"},
    {"title":"Z→K¹ resolves","board":"K5! ZxK","stack":"K>Z | Z>K"},
    {"title":"K¹→Z resolves","board":"K5! ZxK","stack":"Z>K"},
    {"title":"Z→K¹ resolves","board":"K5! ZxK","stack":""},
    {"title":"Kazz refilled, Zakk did not","board":"K5! ZxK","stack":""},
  ],
};
